export { SpreadXClient } from "./client.js";
export { SpreadXApiError } from "./errors.js";
export type {
  AuditEvent,
  AuthenticationAssurance,
  AuthenticationMethod,
  AuthorizationDecision,
  AuthorizationDecisionRequest,
  AuthorizationModel,
  Balance,
  Candle,
  ComplianceProfile,
  ComplianceStatus,
  ConsentRecord,
  ConsentStatus,
  ExecutionCapabilityManifest,
  ExecutionEventType,
  ExecutionIntentType,
  ExecutionQualityStatus,
  ExecutionRiskConstraintType,
  ExecutionState,
  Instrument,
  Order,
  Position,
  PriceLevel,
  RegulatoryReport,
  ReportStatus,
  DecisionReasonCode,
  Entitlement,
  EntitlementAction,
  EntitlementCapabilityManifest,
  EntitlementSubjectType,
  EntitlementStatus,
  EntitlementType,
  SecurityControl,
  Trade,
  VenueProfile,
  WalletAsset,
  WalletTransaction,
} from "./types.js";
